[tool.poetry]
name = "projekt-analiza"
version = "0.1.0"
description = ""
authors = ["Papcer <kacper.plata321@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
ultralytics = "^8.1.20"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
